/**
 * The closed set of machine-readable error codes the API can return.
 * HTTP status mapping lives in exactly one place: src/shared/http/errorHandler.ts.
 */
export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  REQUEST_EXPIRED: 'REQUEST_EXPIRED',
  REPLAY_DETECTED: 'REPLAY_DETECTED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MALFORMED_JSON: 'MALFORMED_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ALREADY_CANCELLED: 'ALREADY_CANCELLED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  RATE_LIMITED: 'RATE_LIMITED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  LLM_UNAVAILABLE: 'LLM_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
